-- ============================================================================
-- Supabase Database Setup
-- Run this in the Supabase SQL Editor to set up the database from scratch.
-- Safe to re-run — uses IF NOT EXISTS / DROP IF EXISTS.
-- ============================================================================

-- ── Enum types ──────────────────────────────────────────────────────────────
DO $$ BEGIN
    CREATE TYPE "public"."Role" AS ENUM ('user', 'admin');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."Gender" AS ENUM ('male', 'female');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."Invitation" AS ENUM ('members', 'non_members', 'alumni', 'all_students', 'non_students');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."Siblings" AS ENUM ('brothers', 'sisters', 'all');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."EventRegistrationStatus" AS ENUM ('pending', 'confirmed', 'cancelled', 'waitlisted');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."EventFormFieldType" AS ENUM ('short_text', 'checkbox_multi', 'radio_single');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."PaymentStatus" AS ENUM ('unpaid', 'paid', 'refunded', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."MembershipPlan" AS ENUM ('single_term', 'two_term');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── Tables ──────────────────────────────────────────────────────────────────

-- users table (profile data, mirrors auth.users.id)
CREATE TABLE IF NOT EXISTS public.users (
    id           UUID          PRIMARY KEY,
    first_name   VARCHAR(50)   NOT NULL,
    last_name    VARCHAR(50)   NOT NULL,
    phone_number VARCHAR(15)   NOT NULL UNIQUE,
    role         "Role"        NOT NULL DEFAULT 'user',
    gender       "Gender"      NOT NULL,
    study_program VARCHAR(50)  NOT NULL,
    term         VARCHAR(4)    NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_public_users_auth_users_id
        FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- events_info
CREATE TABLE IF NOT EXISTS public.events_info (
    id               INT            PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    term             VARCHAR(4)     NOT NULL,
    title            VARCHAR(50)    NOT NULL UNIQUE,
    date             DATE           NOT NULL,
    start_time       TIME           NOT NULL,
    end_time         TIME           NOT NULL,
    deadline         TIMESTAMPTZ    NOT NULL,
    address          VARCHAR(50)    NOT NULL,
    invitation       "Invitation"   NOT NULL DEFAULT 'members',
    siblings         "Siblings"     NOT NULL DEFAULT 'all',
    price_member     INT            NOT NULL DEFAULT 0,
    price_nonmember  INT            NOT NULL DEFAULT -1,
    price_alumnus    INT            NOT NULL DEFAULT -1,
    description      TEXT,
    poster           VARCHAR(255),
    is_published     BOOLEAN        NOT NULL DEFAULT true
);

-- event_registrations
CREATE TABLE IF NOT EXISTS public.event_registrations (
    id                  UUID                      PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id            INT                       NOT NULL REFERENCES public.events_info(id) ON DELETE CASCADE,
    user_id             UUID                      REFERENCES public.users(id) ON DELETE CASCADE,
    status              "EventRegistrationStatus" NOT NULL DEFAULT 'pending',
    invitation_snapshot "Invitation"              NOT NULL,
    siblings_snapshot   "Siblings"                NOT NULL,
    quoted_price         INT                       NOT NULL,
    payment_required     BOOLEAN                   NOT NULL DEFAULT false,
    stripe_session_id    VARCHAR(255),
    payment_status       "PaymentStatus"           NOT NULL DEFAULT 'unpaid',
    payment_completed_at TIMESTAMPTZ,
    submitted_at         TIMESTAMPTZ               NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ               NOT NULL DEFAULT now(),

    CONSTRAINT uniq_member_registration_per_event UNIQUE (event_id, user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_event_registrations_stripe_session
    ON public.event_registrations (stripe_session_id);

CREATE INDEX IF NOT EXISTS idx_event_registrations_event_status
    ON public.event_registrations (event_id, status, submitted_at);
CREATE INDEX IF NOT EXISTS idx_event_registrations_user
    ON public.event_registrations (user_id);

-- event_registration_profiles
CREATE TABLE IF NOT EXISTS public.event_registration_profiles (
    registration_id UUID          PRIMARY KEY REFERENCES public.event_registrations(id) ON DELETE CASCADE,
    first_name      VARCHAR(50)   NOT NULL,
    last_name       VARCHAR(50)   NOT NULL,
    email           VARCHAR(50)   NOT NULL,
    phone_number    VARCHAR(15)   NOT NULL,
    gender          "Gender"      NOT NULL,
    is_student      BOOLEAN       NOT NULL,
    university_name VARCHAR(100)  NOT NULL,
    study_program   VARCHAR(100),
    is_alumnus      BOOLEAN       NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_registration_profile_email_phone
    ON public.event_registration_profiles (email, phone_number);

-- event_form_fields
CREATE TABLE IF NOT EXISTS public.event_form_fields (
    id          UUID                  PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id    INT                   NOT NULL REFERENCES public.events_info(id) ON DELETE CASCADE,
    question    VARCHAR(255)          NOT NULL,
    help_text   VARCHAR(500),
    field_type  "EventFormFieldType"  NOT NULL,
    is_required BOOLEAN               NOT NULL DEFAULT false,
    sort_order  INT                   NOT NULL DEFAULT 0,
    options     JSONB,
    created_at  TIMESTAMPTZ           NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ           NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_event_form_fields_event_sort
    ON public.event_form_fields (event_id, sort_order);

-- event_registration_field_answers
CREATE TABLE IF NOT EXISTS public.event_registration_field_answers (
    id                      UUID                  PRIMARY KEY DEFAULT gen_random_uuid(),
    registration_id         UUID                  NOT NULL REFERENCES public.event_registrations(id) ON DELETE CASCADE,
    field_id                UUID                  NOT NULL REFERENCES public.event_form_fields(id) ON DELETE CASCADE,
    answer_payload          JSONB                 NOT NULL,
    field_type_snapshot     "EventFormFieldType"  NOT NULL,
    field_question_snapshot VARCHAR(255)          NOT NULL,
    created_at              TIMESTAMPTZ           NOT NULL DEFAULT now(),

    CONSTRAINT uniq_registration_answer_per_field UNIQUE (registration_id, field_id)
);

CREATE INDEX IF NOT EXISTS idx_field_answers_registration
    ON public.event_registration_field_answers (registration_id);
CREATE INDEX IF NOT EXISTS idx_field_answers_field
    ON public.event_registration_field_answers (field_id);

-- admin_options
CREATE TABLE IF NOT EXISTS public.admin_options (
    term                          VARCHAR(4)   PRIMARY KEY,
    price_single_term             INT          NOT NULL DEFAULT 150,
    price_discounted_two_term     INT          NOT NULL DEFAULT 300,
    membership_open               BOOLEAN      NOT NULL DEFAULT true,
    is_current                    BOOLEAN      NOT NULL DEFAULT false
);

-- membership_payments
CREATE TABLE IF NOT EXISTS public.membership_payments (
    id                UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id           UUID             NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    term              VARCHAR(4)       NOT NULL,
    plan              "MembershipPlan" NOT NULL,
    amount            INT              NOT NULL,
    stripe_session_id VARCHAR(255)     UNIQUE,
    payment_status    "PaymentStatus"  NOT NULL DEFAULT 'unpaid',
    paid_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ      NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_membership_payments_user_term
    ON public.membership_payments (user_id, term);

-- ── Enable Row Level Security on all tables ─────────────────────────────────

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registration_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_form_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registration_field_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_payments ENABLE ROW LEVEL SECURITY;

-- ── RLS Policies ────────────────────────────────────────────────────────────
-- See also: supabase/sql/rls_policies.sql for the canonical policy definitions.
-- We include core policies here for a complete setup.

-- Helper: SECURITY DEFINER to break recursion cycles
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- users: allow authenticated users to read their own row
DROP POLICY IF EXISTS "users_read_own" ON public.users;
CREATE POLICY "users_read_own" ON public.users
    FOR SELECT
    USING (auth.uid() = id);

-- users: admins can read all rows
DROP POLICY IF EXISTS "admins_read_all_users" ON public.users;
CREATE POLICY "admins_read_all_users" ON public.users
    FOR SELECT
    USING (public.is_admin());

-- Users have NO self-write access: rows are created by the server-side
-- handle_new_user trigger and updated only by admins (or dashboard sessions).
DROP POLICY IF EXISTS "users_insert_own" ON public.users;
DROP POLICY IF EXISTS "users_update_own" ON public.users;

-- events_info: public read for published events, admin read
DROP POLICY IF EXISTS "events_public_read" ON public.events_info;
CREATE POLICY "events_public_read" ON public.events_info
    FOR SELECT
    USING (is_published = true);

DROP POLICY IF EXISTS "events_admin_read" ON public.events_info;
CREATE POLICY "events_admin_read" ON public.events_info
    FOR SELECT
    USING (public.is_admin());

DROP POLICY IF EXISTS "events_admin_write" ON public.events_info;
CREATE POLICY "events_admin_write" ON public.events_info
    FOR ALL
    USING (public.is_admin());

-- event_registrations: authenticated users can read/write own
DROP POLICY IF EXISTS "registrations_own" ON public.event_registrations;
CREATE POLICY "registrations_own" ON public.event_registrations
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "registrations_admin_read" ON public.event_registrations;
CREATE POLICY "registrations_admin_read" ON public.event_registrations
    FOR SELECT
    USING (public.is_admin());

-- admin_options: anyone can read
DROP POLICY IF EXISTS "admin_options_read" ON public.admin_options;
CREATE POLICY "admin_options_read" ON public.admin_options
    FOR SELECT
    USING (true);

-- admin_options: only admins can insert
DROP POLICY IF EXISTS "admin_options_insert" ON public.admin_options;
CREATE POLICY "admin_options_insert" ON public.admin_options
    FOR INSERT
    WITH CHECK (public.is_admin());

-- admin_options: only admins can update
DROP POLICY IF EXISTS "admin_options_update" ON public.admin_options;
CREATE POLICY "admin_options_update" ON public.admin_options
    FOR UPDATE
    USING (public.is_admin());

-- admin_options: only admins can delete
DROP POLICY IF EXISTS "admin_options_delete" ON public.admin_options;
CREATE POLICY "admin_options_delete" ON public.admin_options
    FOR DELETE
    USING (public.is_admin());

-- ── Triggers ────────────────────────────────────────────────────────────────

-- Auto-update updated_at on event_registrations
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_event_registrations_updated_at ON public.event_registrations;
CREATE TRIGGER trg_event_registrations_updated_at
    BEFORE UPDATE ON public.event_registrations
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS trg_event_form_fields_updated_at ON public.event_form_fields;
CREATE TRIGGER trg_event_form_fields_updated_at
    BEFORE UPDATE ON public.event_form_fields
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ── Trigger: auto-create public.users on new auth.users ─────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, first_name, last_name, phone_number, role, gender, study_program, term, created_at)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'phone_number', ''),
    'user',
    COALESCE((NEW.raw_user_meta_data->>'gender')::public."Gender", 'male'),
    COALESCE(NEW.raw_user_meta_data->>'study_program', ''),
    COALESCE(NEW.raw_user_meta_data->>'term', ''),
    NOW()
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- ── Trigger: prevent non-admins from changing roles ─────────────────────────

CREATE OR REPLACE FUNCTION public.check_role_change()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.role IS DISTINCT FROM OLD.role THEN
    -- Enforce only for authenticated app users. Dashboard sessions
    -- (SQL Editor = postgres, Table Editor = service_role) bypass this guard.
    IF COALESCE(auth.role(), '') = 'authenticated' AND NOT public.is_admin() THEN
      RAISE EXCEPTION 'Only admins can change user roles';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS prevent_role_escalation ON public.users;
CREATE TRIGGER prevent_role_escalation
  BEFORE UPDATE ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.check_role_change();

-- ── Trigger: force role='user' on non-admin inserts ────────────────────────

CREATE OR REPLACE FUNCTION public.check_role_insert()
RETURNS TRIGGER AS $$
BEGIN
  IF COALESCE(auth.role(), '') = 'authenticated' AND NOT public.is_admin() THEN
    NEW.role := 'user';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS prevent_role_insert_escalation ON public.users;
CREATE TRIGGER prevent_role_insert_escalation
  BEFORE INSERT ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.check_role_insert();
